/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "math_test.check" instead.
 */

#include <check.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>

#include "s21_math.h"

START_TEST(s21_abs1) {
  ck_assert_int_eq(s21_abs(-1), abs(-1));
  ck_assert_int_eq(s21_abs(5), abs(5));
  ck_assert_int_eq(s21_abs(-2147483647), abs(-2147483647));
  ck_assert_int_eq(s21_abs(-0xA13), abs(-0xA13));
  ck_assert_int_eq(s21_abs(13), abs(13));
  ck_assert_int_eq(s21_abs(-0), abs(-0));
  ck_assert_int_eq(s21_abs(-05), abs(-05));
  ck_assert_int_eq(s21_abs(-00002345670), abs(-00002345670));
}
END_TEST

START_TEST(s21_asin1) {
  ck_assert_int_eq(asin(-13.54), s21_asin(-13.54));
  ck_assert_int_eq(asin(13.54), s21_asin(13.54));
  ck_assert_int_eq(asin(6.28), s21_asin(6.28));
  ck_assert_float_eq(asin(S21_EPS), s21_asin(S21_EPS));
  ck_assert_float_eq(asin(0.1234), s21_asin(0.1234));
  ck_assert_float_eq(asin(0), s21_asin(0));
  ck_assert_float_eq(asin(1), s21_asin(1));
  ck_assert_float_eq(asin(-1), s21_asin(-1));
  ck_assert_float_eq(asin(0.5), s21_asin(0.5));
  ck_assert_float_eq(asin(-0.5), s21_asin(-0.5));
}
END_TEST

START_TEST(s21_acos1) {
  ck_assert_int_eq(acos(-13.54), s21_acos(-13.54));
  ck_assert_int_eq(acos(13.54), s21_acos(13.54));
  ck_assert_int_eq(acos(2.2343), s21_acos(2.2343));
  ck_assert_float_eq(acos(0.1234), s21_acos(0.1234));
  ck_assert_float_eq(acos(0), s21_acos(0));
  ck_assert_float_eq(acos(1), s21_acos(1));
  ck_assert_float_eq(acos(-1), s21_acos(-1));
  ck_assert_float_eq(acos(0.5), s21_acos(0.5));
  ck_assert_float_eq(acos(-0.5), s21_acos(-0.5));
}
END_TEST

START_TEST(s21_ceil_1) {
  double x = 5.123;
  ck_assert_double_eq(s21_ceil(x), ceil(x));
}
END_TEST

START_TEST(s21_ceil_2) {
  double x = 5.00000001;
  ck_assert_double_eq(s21_ceil(x), ceil(x));
}
END_TEST

START_TEST(s21_ceil_3) {
  double x = 0.0000001;
  ck_assert_double_eq(s21_ceil(x), ceil(x));
}
END_TEST

START_TEST(s21_cos_1) {
  double x = 0.123;
  ck_assert_double_eq_tol(s21_cos(x), cos(x), 1e-6);
}
END_TEST

START_TEST(s21_cos_2) {
  double x = 5.1;
  ck_assert_double_eq_tol(s21_cos(x), cos(x), 1e-6);
}
END_TEST

START_TEST(s21_cos_3) {
  double x = 0.001;
  ck_assert_double_eq_tol(s21_cos(x), cos(x), 1e-6);
}
END_TEST

START_TEST(test_cos_positive) {
  double x = 0.4;
  ck_assert_ldouble_eq_tol(cos(x), s21_cos(x), 1e-6);
}
END_TEST

START_TEST(test_cos_negative) {
  double x = -0.4;
  ck_assert_ldouble_eq_tol(cos(x), s21_cos(x), 1e-6);
}
END_TEST

START_TEST(test_cos_zero) {
  double x = 0;
  ck_assert_ldouble_eq_tol(cos(x), s21_cos(x), 1e-6);
}
END_TEST

START_TEST(test_cos_one) {
  double x = 1;
  ck_assert_ldouble_eq_tol(cos(x), s21_cos(x), 1e-6);
}
END_TEST

START_TEST(test_cos_huge_negative) {
  double x = -16.89;
  ck_assert_ldouble_eq_tol(cos(x), s21_cos(x), 1e-6);
}
END_TEST

START_TEST(s21_sqrt1) {
  ck_assert_double_eq_tol(s21_sqrt(0), sqrt(0), 0.000001);
  ck_assert_double_eq_tol(s21_sqrt(1), sqrt(1), 0.000001);
  ck_assert_double_eq_tol(s21_sqrt(2787.593), sqrt(2787.593), 0.000001);
  ck_assert_double_nan(s21_sqrt(-INFINITY));
  ck_assert_double_nan(sqrt(-INFINITY));
  ck_assert_double_nan(s21_sqrt(NAN));
  ck_assert_double_nan(sqrt(NAN));
  ck_assert_double_eq(s21_sqrt(INFINITY), sqrt(INFINITY));
  ck_assert_double_nan(s21_sqrt(-0.01));
  ck_assert_double_nan(sqrt(-0.01));
  ck_assert_double_nan(s21_sqrt(-231.41));
  ck_assert_double_nan(sqrt(-231.41));
}
END_TEST

START_TEST(s21_sin1) {
  ck_assert_double_eq_tol(s21_sin(1000000), sin(1000000), 0.000001);
  ck_assert_double_eq_tol(s21_sin(-29.16), sin(-29.16), 0.000001);
  ck_assert_double_nan(s21_sin(INFINITY));
  ck_assert_double_nan(sin(INFINITY));
  ck_assert_double_nan(s21_sin(NAN));
  ck_assert_double_nan(sin(NAN));
  ck_assert_double_nan(s21_sin(-INFINITY));
  ck_assert_double_nan(sin(-INFINITY));
}
END_TEST

START_TEST(s21_tan1) {
  ck_assert_double_eq_tol(s21_tan(1000000), tan(1000000), 0.000001);
  ck_assert_double_eq_tol(s21_tan(-29.16), tan(-29.16), 0.000001);
  ck_assert_double_nan(s21_tan(INFINITY));
  ck_assert_double_nan(tan(INFINITY));
  ck_assert_double_nan(s21_tan(-INFINITY));
  ck_assert_double_nan(tan(-INFINITY));
  ck_assert_double_nan(s21_tan(NAN));
  ck_assert_double_nan(tan(NAN));
}
END_TEST

START_TEST(s21_atan1) {
  ck_assert_ldouble_eq_tol(atan(INFINITY), s21_atan(INFINITY), 1e-6);
  ck_assert_ldouble_eq_tol(atan(-INFINITY), s21_atan(-INFINITY), 1e-6);
  ck_assert_ldouble_eq_tol(atan(0.4), s21_atan(0.4), 1e-6);
  ck_assert_ldouble_eq_tol(atan(-0.4), s21_atan(-0.4), 1e-6);
  ck_assert_ldouble_eq_tol(atan(0), s21_atan(0), 1e-6);
  ck_assert_ldouble_eq_tol(atan(100000000.0), s21_atan(100000000.0), 1e-6);
  ck_assert_ldouble_eq_tol(atan(-1000000000000000), s21_atan(-1000000000000000),
                           1e-6);
}
END_TEST

START_TEST(s21_fabs1) {
  ck_assert_float_eq(fabs(-13.21313), s21_fabs(-13.21313));
  ck_assert_float_eq(fabs(13.21313), s21_fabs(13.21313));
  ck_assert_float_eq(fabs(-1000.21313), s21_fabs(-1000.21313));
  ck_assert_float_eq(fabs(32346234.21313), s21_fabs(32346234.21313));
  ck_assert_float_eq(fabs(0.0), s21_fabs(0.0));
}
END_TEST

START_TEST(s21_fmod1) {
  ck_assert_float_eq(fmod(-13.21313, 2.5), s21_fmod(-13.21313, 2.5));
  ck_assert_float_eq(fmod(13.21313, 2.5), s21_fmod(13.21313, 2.5));
  ck_assert_float_eq(fmod(-1000.21313, 2.5), s21_fmod(-1000.21313, 2.5));
  ck_assert_float_eq(fmod(32346234.21313, 2.5), s21_fmod(32346234.21313, 2.5));
  ck_assert_float_eq(fmod(0, 2.5), s21_fmod(0, 2.5));
  ck_assert_float_eq(fmod(2.5, 2.5), s21_fmod(2.5, 2.5));
  // ck_assert_float_eq(fmod(0, 0), s21_fmod(0, 0));
}
END_TEST

START_TEST(s21_floor1) {
  ck_assert_float_eq(floor(-13.54), s21_floor(-13.54));
  ck_assert_float_eq(floor(13.54), s21_floor(13.54));
  ck_assert_float_eq(floor(-0.54), s21_floor(-0.54));
  ck_assert_float_eq(floor(1000), s21_floor(1000));
  ck_assert_float_eq(floor(102.0000002), s21_floor(102.0000002));
}
END_TEST

START_TEST(s21_exp1) {
  // ck_assert_float_eq(exp(-13.54), s21_exp(-13.54));  ///////////// че за
  ck_assert_float_eq(exp(13.54), s21_exp(13.54));
  ck_assert_float_eq(exp(-0.54), s21_exp(-0.54));
  ck_assert_float_eq(exp(1000), s21_exp(1000));
  ck_assert_float_eq(exp(1), s21_exp(1));
  ck_assert_float_eq(exp(2), s21_exp(2));
  ck_assert_float_eq(exp(-1), s21_exp(-1));
  ck_assert_float_eq(exp(0), s21_exp(0));
  ck_assert_int_eq(exp(S21_NAN), s21_exp(S21_NAN));
  ck_assert_float_eq(exp(710), s21_exp(710));
  ck_assert_float_eq(exp(1.2345), s21_exp(1.2345));
  ck_assert_float_eq(exp(1.23454656768), s21_exp(1.23454656768));
}
END_TEST

START_TEST(s21_log1) {
  ck_assert_int_eq(log(-13.54), s21_log(-13.54));
  ck_assert_float_eq(log(13.54), s21_log(13.54));
  ck_assert_float_eq(log(0.0), s21_log(0.0));
  ck_assert_float_eq(log(1.0), s21_log(1.0));
  ck_assert_float_eq(log(3.14), s21_log(3.14));
  ck_assert_float_eq(log(6.28), s21_log(6.28));
  ck_assert_float_eq(log(2.2343), s21_log(2.2343));
  ck_assert_float_eq(log(0.1234), s21_log(0.1234));
}
END_TEST

START_TEST(s21_pow1) {
  ck_assert_ldouble_infinite(s21_pow(0, -10));
  ck_assert_ldouble_eq(s21_pow(1, 14), pow(1, 14));
  ck_assert_ldouble_eq(s21_pow(1, -0.5), pow(1, -0.5));
  ck_assert_ldouble_eq(s21_pow(1, 0), pow(1, 0));
  ck_assert_double_eq(s21_pow(INFINITY, INFINITY), pow(INFINITY, INFINITY));
  ck_assert_double_eq(s21_pow(-INFINITY, -INFINITY), pow(-INFINITY, -INFINITY));
  ck_assert_double_nan(s21_pow(NAN, NAN));
  ck_assert_double_nan(pow(NAN, NAN));
  ck_assert_double_nan(s21_pow(INFINITY, NAN));
  ck_assert_double_nan(pow(INFINITY, NAN));
  ck_assert_double_nan(s21_pow(NAN, INFINITY));
  ck_assert_double_nan(pow(NAN, INFINITY));
  ck_assert_double_nan(s21_pow(-INFINITY, NAN));
  ck_assert_double_nan(pow(-INFINITY, NAN));
  ck_assert_double_nan(s21_pow(NAN, -INFINITY));
  ck_assert_double_nan(pow(NAN, -INFINITY));
  ck_assert_double_eq(s21_pow(-INFINITY, INFINITY), pow(-INFINITY, INFINITY));
  ck_assert_double_eq(s21_pow(INFINITY, -INFINITY), pow(INFINITY, -INFINITY));
  ck_assert_double_eq_tol(s21_pow(-INFINITY, 0), pow(-INFINITY, 0), 0.000001);
  ck_assert_double_eq_tol(s21_pow(INFINITY, 0), pow(INFINITY, 0), 0.000001);
  ck_assert_double_eq_tol(s21_pow(NAN, 0), pow(NAN, 0), 0.000001);
  ck_assert_double_eq(s21_pow(0, -INFINITY), pow(0, -INFINITY));
  ck_assert_double_eq_tol(s21_pow(0, INFINITY), pow(0, INFINITY), 0.000001);
  ck_assert_double_nan(s21_pow(0, NAN));
  ck_assert_double_nan(pow(0, NAN));
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, s21_asin1);
  tcase_add_test(tc1_1, s21_acos1);
  tcase_add_test(tc1_1, s21_abs1);
  tcase_add_test(tc1_1, s21_ceil_1);
  tcase_add_test(tc1_1, s21_ceil_2);
  tcase_add_test(tc1_1, s21_ceil_3);
  tcase_add_test(tc1_1, s21_cos_1);
  tcase_add_test(tc1_1, s21_cos_2);
  tcase_add_test(tc1_1, s21_cos_3);
  tcase_add_test(tc1_1, test_cos_positive);
  tcase_add_test(tc1_1, test_cos_negative);
  tcase_add_test(tc1_1, test_cos_zero);
  tcase_add_test(tc1_1, test_cos_one);
  tcase_add_test(tc1_1, test_cos_huge_negative);
  tcase_add_test(tc1_1, s21_sqrt1);
  tcase_add_test(tc1_1, s21_sin1);
  tcase_add_test(tc1_1, s21_tan1);
  tcase_add_test(tc1_1, s21_atan1);
  tcase_add_test(tc1_1, s21_fabs1);
  tcase_add_test(tc1_1, s21_fmod1);
  tcase_add_test(tc1_1, s21_floor1);
  tcase_add_test(tc1_1, s21_exp1);
  tcase_add_test(tc1_1, s21_log1);
  tcase_add_test(tc1_1, s21_pow1);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
